[package]
name = "rsbackup"
version = "0.1.0"
authors = ["Arc676/Alessandro Vinciguerra <alesvinciguerra@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
